In [1]:
import tensorflow as tf
import numpy as np

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


![image](https://user-images.githubusercontent.com/51112316/60850464-6e0a3680-a22a-11e9-84da-c88c74e847cf.png)

### 위의 형태로 간단하게 표현할 수 없으므로 matrix로 표현하기 위해 두 개의 층으로 생각한다.

![image](https://user-images.githubusercontent.com/51112316/60850525-c04b5780-a22a-11e9-8b64-98bfc4d38d63.png)

### XOR 게이트

In [23]:
x_data=np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
y_data=np.array([[0],[1],[1],[0]],dtype=np.float32)

##### layer1

In [24]:
X=tf.placeholder(tf.float32)
Y=tf.placeholder(tf.float32)
W1=tf.Variable(tf.random_normal([2,2]),name='weight1')  # [2,2] => [(x1,x2),출력값2개] : 즉 2개의 모형을 만들어냄
b1=tf.Variable(tf.random_normal([2]),name='bias1')      # [2]   => 출력값 2개
layer1=tf.sigmoid(tf.matmul(X,W1)+b1)

##### layer2

In [ ]:
W2=tf.Variable(tf.random_normal([2,1]),name='weight2')  # 2개의 모형을 입력받고 1개의 값을 출력
b2=tf.Variable(tf.random_normal([1]),name='bias2')      # 1개의 출력값
hypothesis=tf.sigmoid(tf.matmul(layer1,W2)+b2)          

### cost / loss function

In [25]:
cost = -tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

### Accuracy computation

#### True if hypothesis > 0.2 else False

In [26]:
predicted = tf.cast(hypothesis > 0.2, dtype=tf.float32)     # 0.2 > 이면 1, 0.2 < 이면 0
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted,Y),dtype=tf.float32))

### Launch graph

In [27]:
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    for step in range(10001) :
        sess.run(train, feed_dict={X:x_data,Y:y_data})
        if step % 500 == 0:     # 500번마다 프린트
            print("step :",step,"\ncost :",sess.run(cost,feed_dict={X:x_data,Y:y_data}),
                 "\nWeight :\n",sess.run([W1,W2]),'\nbias :\n',sess.run([b1,b2]))
            h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data,Y:y_data})
            print('Hypothesis:\n',h,'\nCorrect:\n',c,'\nAccuracy:',a)

step : 0 
cost : 0.7723893 
Weight :
 [array([[ 0.37515682,  0.8297534 ],
       [-2.0416334 , -0.581933  ]], dtype=float32), array([[0.6933819],
       [1.3172324]], dtype=float32)] 
bias :
 [array([ 0.1319074, -0.3962426], dtype=float32), array([-0.03410342], dtype=float32)]
Hypothesis:
 [[0.70375246]
 [0.6023556 ]
 [0.76813835]
 [0.66789514]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy: 0.5
step : 500 
cost : 0.68716115 
Weight :
 [array([[ 0.5521833 ,  0.7772787 ],
       [-2.1099398 , -0.88166004]], dtype=float32), array([[0.3953385],
       [1.0957754]], dtype=float32)] 
bias :
 [array([-0.11699541, -0.8657465 ], dtype=float32), array([-0.46585226], dtype=float32)]
Hypothesis:
 [[0.51119065]
 [0.43418956]
 [0.5739121 ]
 [0.47444934]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy: 0.5
step : 1000 
cost : 0.67725766 
Weight :
 [array([[ 0.74390393,  1.0637742 ],
       [-2.190307  , -1.2897465 ]], dtype=float32), array([[0.41364253],
       [1.2605097 ]], dtype=float32)] 
bias :


#### 10000번째를 살펴보면,

w11=(5.9086995,-5.666097) : 첫번째 모형의 가중치

w12=(6.413603,-6.524489)

=> layer1의 출력값

w21=-9.222211

w22=- 9.710787

=>layer2의 출력값

bias1(b1)=( 2.7884657(첫번째 모형의 b값),-3.4976137(2번째 모형의 b값))

bias2(b2)=(4.2758474)

=> 결과값(예측값)
Hypothesis:
 [[0.01588096]
 [0.9777956 ]
 [0.98617065]
 [0.01349245]] 

### 은닉층의 안의 구조 :  퍼셉트론이 7개인 경우

![image](https://user-images.githubusercontent.com/51112316/60852759-06f17f80-a234-11e9-816d-6d8ac7ddb954.png)

![image](https://user-images.githubusercontent.com/51112316/60852764-0eb12400-a234-11e9-8159-c083757ac737.png)

##### layer1

In [42]:
X=tf.placeholder(tf.float32)
Y=tf.placeholder(tf.float32)
W1=tf.Variable(tf.random_normal([2,7]),name='weight1')  # [2,2] => [(x1,x2),출력값2개] : 즉 2개의 모형을 만들어냄
b1=tf.Variable(tf.random_normal([7]),name='bias1')      # [2]   => 출력값 2개
layer1=tf.sigmoid(tf.matmul(X,W1)+b1)

##### layer2

In [43]:
W2=tf.Variable(tf.random_normal([7,1]),name='weight2')
b2=tf.Variable(tf.random_normal([1]),name='bias2')
hypothesis=tf.sigmoid(tf.matmul(layer1,W2)+b2)

##### cost / loss function

In [44]:
cost = -tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

###### Accuracy computation
###### True if hypothesis > 0.2 else False

In [45]:
predicted = tf.cast(hypothesis > 0.2, dtype=tf.float32)     # 0.2 > 이면 1, 0.2 < 이면 0
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted,Y),dtype=tf.float32))

##### Launch graph

In [46]:
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    for step in range(10001) :
        sess.run(train, feed_dict={X:x_data,Y:y_data})
        if step % 500 == 0:     # 500번마다 프린트
            print("step :",step,"\ncost :",sess.run(cost,feed_dict={X:x_data,Y:y_data}),
                 "\nWeight :\n",sess.run([W1,W2]),'\nbias :\n',sess.run([b1,b2]))
            h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data,Y:y_data})
            print('Hypothesis:\n',h,'\nCorrect:\n',c,'\nAccuracy:',a)

step : 0 
cost : 0.7632902 
Weight :
 [array([[ 0.94638526,  0.27276212,  0.7511661 ,  0.43128988,  1.3717607 ,
         1.5737258 ,  0.6938013 ],
       [ 0.18680137, -0.9290862 , -0.51055926, -2.5747712 , -0.33917475,
         0.99480885, -1.2748907 ]], dtype=float32), array([[-0.96582836],
       [-0.11308346],
       [ 0.00577434],
       [ 0.3860457 ],
       [ 0.00603792],
       [ 0.15622152],
       [ 1.567502  ]], dtype=float32)] 
bias :
 [array([ 1.0751519 ,  0.00249732,  1.3770708 ,  2.1965582 , -1.0358906 ,
        0.23183297,  1.0126367 ], dtype=float32), array([0.03165315], dtype=float32)]
Hypothesis:
 [[0.6996217 ]
 [0.55266505]
 [0.71992564]
 [0.60498744]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy: 0.5
step : 500 
cost : 0.65624917 
Weight :
 [array([[ 1.0465928 ,  0.25597   ,  0.8194302 ,  0.5081079 ,  1.3721523 ,
         1.8219789 ,  0.11669454],
       [-0.44905087, -0.917902  , -0.61971754, -2.5583792 , -0.3403378 ,
         1.416168  , -1.1858271 ]], dtype=flo

step : 6000 
cost : 0.015621582 
Weight :
 [array([[ 4.763789 ,  0.5540649,  2.3941658,  4.5373597,  2.0682592,
         5.183768 ,  2.7101362],
       [-3.4387357, -2.2899919, -1.5546257, -3.9003704, -2.9196775,
         4.796106 , -5.224873 ]], dtype=float32), array([[-5.263391 ],
       [ 2.234949 ],
       [-1.881616 ],
       [-4.746132 ],
       [ 2.9807477],
       [ 6.544415 ],
       [ 6.8102503]], dtype=float32)] 
bias :
 [array([ 1.6690116 ,  0.13127242,  1.2684207 ,  2.1863537 , -1.1514368 ,
       -1.5002083 , -0.7098187 ], dtype=float32), array([-0.11450798], dtype=float32)]
Hypothesis:
 [[0.00715046]
 [0.985193  ]
 [0.98293877]
 [0.02291731]] 
Correct:
 [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy: 1.0
step : 6500 
cost : 0.013618505 
Weight :
 [array([[ 4.826145  ,  0.57016647,  2.4342775 ,  4.6035185 ,  2.1061666 ,
         5.2143884 ,  2.7853153 ],
       [-3.4879737 , -2.337794  , -1.5860486 , -3.9393752 , -2.9950044 ,
         4.8346744 , -5.2885246 ]], dtype=float32), array(

Weight 1

: 입력값(x1,x2)가 2개이므로 각각 7개씩 쌍으로 필요.

W11= [ 5.1159596 ,  0.65125626,  2.636992  ,  4.910855  ,  2.2894127 , 5.351424  ,  3.1272488 ]

W12= [-3.716154  , -2.5676327 , -1.7400672 , -4.1220684 , -3.348719  , 5.0124087 , -5.5757074 ]

Bias1 = [ 1.715595  ,  0.15898353,  1.1918973 ,  2.1689854 , -1.1563903 ,   -1.5645443 , -0.96809393]

Weight 2

모형이 1개만 남오면 되므로 1개만 필요.

W2= [-5.85684  ],
    [ 2.593283 ],
    [-2.103122 ],
    [-5.3461566],
    [ 3.5310051],
    [ 7.001428 ],
    [ 7.6000314]
    
Bias2 =  [0.0268142]

###   
###   
### 복잡한 모형 : 은닉층 3개

![image](https://user-images.githubusercontent.com/51112316/60853369-c1828180-a236-11e9-911d-7c5f9004852f.png)

In [56]:
x_data = np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
y_data=np.array([[0],[1],[1],[0]],dtype=np.float32)
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [57]:
W1=tf.Variable(tf.random_normal([2,3]),name='weight1')
b1=tf.Variable(tf.random_normal([3]),name='bias1')
layer1=tf.sigmoid(tf.matmul(X,W1)+b1)

In [58]:
W2=tf.Variable(tf.random_normal([3,3]),name='weight2')
b2=tf.Variable(tf.random_normal([3]),name='bias2')
layer2=tf.sigmoid(tf.matmul(layer1,W2)+b2)

In [59]:
W3=tf.Variable(tf.random_normal([3,1]),name='weight3')
b3=tf.Variable(tf.random_normal([1]),name='bias3')
hypothesis=tf.sigmoid(tf.matmul(layer2,W3)+b3)

In [60]:
cost = -tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [61]:
predicted = tf.cast(hypothesis > 0.2, dtype=tf.float32)     # 0.2 > 이면 1, 0.2 < 이면 0
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted,Y),dtype=tf.float32))

In [62]:
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    for step in range(10001) :
        sess.run(train, feed_dict={X:x_data,Y:y_data})
        if step % 500 == 0:     # 500번마다 프린트
            print("step :",step,"\ncost :",sess.run(cost,feed_dict={X:x_data,Y:y_data}),
                 "\nWeight :\n",sess.run([W1,W2,W3]),'\nbias :\n',sess.run([b1,b2,b3]))
            h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X:x_data,Y:y_data})
            print('Hypothesis:\n',h,'\nCorrect:\n',c,'\nAccuracy:',a)

step : 0 
cost : 0.7457803 
Weight :
 [array([[ 0.6011463 , -1.1061989 ,  1.1738261 ],
       [ 0.02326491,  1.6290165 , -0.36408186]], dtype=float32), array([[ 0.57873696,  0.59983873,  1.5387963 ],
       [ 0.6974988 ,  0.71224594, -1.9175724 ],
       [-0.7895747 ,  1.0017688 , -1.160519  ]], dtype=float32), array([[-0.6040131 ],
       [-0.37879583],
       [ 0.46802682]], dtype=float32)] 
bias :
 [array([-0.5661251, -1.5089496,  0.5207312], dtype=float32), array([ 0.22580446, -1.700356  , -0.00969983], dtype=float32), array([-0.32043353], dtype=float32)]
Hypothesis:
 [[0.35839465]
 [0.33205712]
 [0.36456454]
 [0.34808397]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy: 0.5
step : 500 
cost : 0.69520324 
Weight :
 [array([[ 0.62496895, -0.885404  ,  1.1881583 ],
       [-0.01040086,  1.5733413 , -0.3993628 ]], dtype=float32), array([[ 0.5650959 ,  0.5872616 ,  1.5393873 ],
       [ 0.62160003,  0.66377366, -1.8670844 ],
       [-0.79268223,  0.9920049 , -1.1803246 ]], dtype=float32

step : 6000 
cost : 0.5898825 
Weight :
 [array([[ 0.48178563, -1.8139665 ,  2.7505126 ],
       [ 0.11989031,  2.1363876 , -2.236284  ]], dtype=float32), array([[ 0.39051032,  0.5610845 ,  1.5240018 ],
       [ 1.9965526 ,  0.410722  , -1.8702742 ],
       [-2.7671242 ,  1.475719  , -1.176987  ]], dtype=float32), array([[ 2.8082075 ],
       [-0.82736224],
       [ 0.0375375 ]], dtype=float32)] 
bias :
 [array([-0.629218 , -1.55672  ,  1.4074534], dtype=float32), array([-0.1486911 , -1.5975538 , -0.07222483], dtype=float32), array([-0.25684616], dtype=float32)]
Hypothesis:
 [[0.43539748]
 [0.76489145]
 [0.37889326]
 [0.42268917]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy: 0.5
step : 6500 
cost : 0.5363772 
Weight :
 [array([[ 0.41560775, -2.1607993 ,  3.284133  ],
       [ 0.18807246,  2.4659657 , -2.772661  ]], dtype=float32), array([[ 0.3416004 ,  0.5423894 ,  1.5355793 ],
       [ 2.550678  ,  0.51317376, -1.8886744 ],
       [-3.5924232 ,  1.5436614 , -1.1642693 ]], dtype=floa

![image](https://user-images.githubusercontent.com/51112316/60854572-b8e07a00-a23b-11e9-94c5-9e4012ff62ae.png)


#### layer1에 해당하는 w 값은 2개씩(입력) 3쌍(출력)이 나와야 함.

w11=  (2.0166306,-1.2480559)

w12=  (-3.5973318,4.4985313)

w13=  ( 4.801366,-4.5496526)

#### layer2에 해당하는 w값은 3개씩(입력) 3쌍(출력)이 나와야 함.

w21= (-0.34071702,3.5740862,-6.440118)
w22= (-0.81755817,2.8193772, 2.0331237)
w23= (3.1814697,-5.120784 ,-0.43251756)

#### layer3에 해당하는 w값은 3개씩(입력) 1개 이 나와야 함.
w31=([ 7.24     ],[-4.3638086],[ 6.2379184])

##   
##    

# 층 : 4개, 노드 : 10개 vs 층 : 2개, 노드 : 10개

## => 결과값은 같으나 층이 많을수록 

##       0에 가까운 것은 0에 더욱 가깝고 

##       1에 가까운 것은 1에 더욱 가깝다.

##       복잡한 모델일수록 좋다.


![image](https://user-images.githubusercontent.com/51112316/60854667-078e1400-a23c-11e9-8256-17be8770017f.png)

![image](https://user-images.githubusercontent.com/51112316/60854775-5f2c7f80-a23c-11e9-9106-b7b09c7a0035.png)

# XOR 실습예제

## 접근풀이 및 조건

### Neural Net에 대한 개념과 이해가 필요하다.

### XOR 문제의 속성과 그 내용을 파악할 수 있어야 한다.

### 1. 제공된 데이터(xor.txt)를 이용하여 XOR문제에 대한 실습코드를 작성하고 그 정확도를 측정하시오.

![image](https://user-images.githubusercontent.com/51112316/60855170-a9fac700-a23d-11e9-870d-a8c6a2e27d36.png)

In [85]:
x_data=np.array([[0,0],[1,1],[1,0],[0,1]],dtype=np.float32)
y_data=np.array([[0],[0],[1],[1]],dtype=np.float32)
X=tf.placeholder(tf.float32)
Y=tf.placeholder(tf.float32)

#### 단일 포셉트론으로 비선형적 모델 해결 X

#### => layer 최소 2개 이상

In [86]:
W1=tf.Variable(tf.random_uniform([2,2],-1.0,1.0))
W2=tf.Variable(tf.random_uniform([2,1],-1.0,1.0))

b1=tf.Variable(tf.zeros([2]),name='Bias1')
b2=tf.Variable(tf.zeros([1]),name='Bias2')

In [87]:
L2=tf.sigmoid(tf.matmul(X,W1)+b1)
hypothesis=tf.sigmoid(tf.matmul(L2,W2)+b2)

In [88]:
cost=-tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))

#### For this time, learning rate is very important!!!

In [89]:
learning_rate=0.1
optimizer=tf.train.GradientDescentOptimizer(learning_rate)
train=optimizer.minimize(cost)
init=tf.global_variables_initializer()

In [90]:
#Blas GEMM launch failed 오류시 아래 코드 사용
#gpu_options=tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
#sess=tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

In [92]:
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(20001):
        sess.run(train, feed_dict={X:x_data,Y:y_data})
        if step % 500==0:
            print(step,sess.run(cost,feed_dict={X:x_data,Y:y_data}))
    
    #TEST MODEL
    correct=tf.equal(tf.floor(hypothesis+0.5),Y)
    #CALCULATE ACCURACY
    accuracy=tf.reduce_mean(tf.cast(correct,"float"))
    print(sess.run([hypothesis],feed_dict={X:x_data,Y:y_data}))
    print("Accuracy:",accuracy.eval({X:x_data,Y:y_data}))

0 0.7151514
500 0.69123125
1000 0.6875614
1500 0.6764374
2000 0.64055675
2500 0.5663675
3000 0.48846874
3500 0.43620145
4000 0.40712786
4500 0.39068606
5000 0.3806538
5500 0.37406588
6000 0.36947417
6500 0.36611944
7000 0.36357534
7500 0.36158752
8000 0.35999584
8500 0.35869545
9000 0.35761452
9500 0.35670328
10000 0.35592532
10500 0.3552538
11000 0.35466892
11500 0.35415518
12000 0.35370046
12500 0.35329536
13000 0.35293242
13500 0.35260525
14000 0.35230917
14500 0.3520397
15000 0.3517937
15500 0.35156825
16000 0.35136086
16500 0.35116965
17000 0.35099268
17500 0.35082814
18000 0.35067528
18500 0.35053265
19000 0.3503994
19500 0.35027456
20000 0.35015738
[array([[0.00445532],
       [0.50120395],
       [0.9965611 ],
       [0.49799687]], dtype=float32)]
Accuracy: 0.5


# NAND 문제

#### 제공된 데이터를 이용하여 NAND 문제에 대한 실습 코드를 작성하고 그 정확도를 측정하시오.

In [93]:
cd C:\Users\최재혁\Desktop\인공신경망

C:\Users\최재혁\Desktop\인공신경망


In [97]:
xy=np.loadtxt('NANDdata.txt',unpack=True)

In [100]:
x_data=np.transpose(xy[0:-1])
y_data=np.reshape(xy[-1],(4,1))

X=tf.placeholder(tf.float32)
Y=tf.placeholder(tf.float32)

#### Define 2 layer Neural Network

In [101]:
W1 = tf.Variable(tf.random_uniform([2,2],-1.0,1.0))
W2 = tf.Variable(tf.random_uniform([2,2],-1.0,1.0))

b1=tf.Variable(tf.zeros([2]),name='bias1')
b2=tf.Variable(tf.zeros([1]),name='bias2')

#### Our hypothesis

In [102]:
L2=tf.sigmoid(tf.matmul(X,W1)+b1)
hypothesis=tf.sigmoid(tf.matmul(L2,W2)+b2)

#### Cross entropy cost function

In [104]:
cost= -tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))

#### For this time, learning rate is very important.

In [105]:
learning_rate=0.1
optimizer=tf.train.GradientDescentOptimizer(learning_rate)
train=optimizer.minimize(cost)
init=tf.global_variables_initializer()

In [106]:
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(10001):
        sess.run(train, feed_dict={X:x_data,Y:y_data})
        if step % 500==0:
            print(step,sess.run(cost,feed_dict={X:x_data,Y:y_data}))
    
    #TEST MODEL
    correct=tf.equal(tf.floor(hypothesis+0.5),Y)
    #CALCULATE ACCURACY
    accuracy=tf.reduce_mean(tf.cast(correct,"float"))
    print(sess.run([hypothesis],feed_dict={X:x_data,Y:y_data}))
    print("Accuracy:",accuracy.eval({X:x_data,Y:y_data}))

0 0.65722024
500 0.4304848
1000 0.27081937
1500 0.15577346
2000 0.09677754
2500 0.06629323
3000 0.048905402
3500 0.03801536
4000 0.03068535
4500 0.025479354
5000 0.02162851
5500 0.0186881
6000 0.016384488
6500 0.014540827
7000 0.013038309
7500 0.01179457
8000 0.010750878
8500 0.009864619
9000 0.009104019
9500 0.008445123
10000 0.007869514
10500 0.0073628933
11000 0.0069139553
11500 0.0065136394
12000 0.006154732
12500 0.0058312793
13000 0.005538448
13500 0.0052721417
14000 0.0050290236
14500 0.0048063425
15000 0.0046016024
15500 0.0044127684
16000 0.004238139
16500 0.0040761735
17000 0.0039256187
17500 0.0037853043
18000 0.0036542052
18500 0.0035315442
19000 0.0034164705
19500 0.0033083884
20000 0.0032066202
[array([[0.9996741 , 0.99967265],
       [0.99698174, 0.996973  ],
       [0.99722487, 0.9972164 ],
       [0.00665703, 0.00667706]], dtype=float32)]
Accuracy: 1.0
