In [17]:
cd C:\Users\최재혁\Desktop\인공신경망

C:\Users\최재혁\Desktop\인공신경망


In [3]:
! pip install tensorflow --user

  Using cached https://files.pythonhosted.org/packages/bf/4a/5c86ed8b245aa48f9f819b13a0a9039e9126ba19fdd0c7e0b8026c12315a/tensorflow-1.14.0-cp36-cp36m-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/20/ed/e036d31a9b2c750f270cbb1cfc1c0f94ac78ae504eea7eec3267be4e294a/numpy-1.16.4-cp36-cp36m-win_amd64.whl
  Using cached https://files.pythonhosted.org/packages/d0/33/376510eb8d6246f3c30545f416b2263eee461e40940c2a4413c711bdf62d/google_pasta-0.1.7-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/91/2d/2ed263449a078cd9c8a9ba50ebd50123adf1f8cfbea1492f9084169b89d9/tensorboard-1.14.0-py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/d1/4f/950dfae467b384fc96bc6469de25d832534f6b4441033c39f914efd13418/astor-0.8.0-py2.py3-none-any.whl
  Using cached https://files.python

ERROR: tensorboard 1.14.0 has requirement setuptools>=41.0.0, but you'll have setuptools 39.1.0 which is incompatible.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [8]:
import tensorflow as tf

In [9]:
import numpy as np

In [5]:
hello=tf.constant('Hello, TensorFlow!')
sess=tf.Session()
print(sess.run(hello))

b'Hello, TensorFlow!'


In [6]:
a=tf.constant(10)
b=tf.constant(32)
print(sess.run(a+b))

42


In [11]:
x_data=np.array([[0,0],[0,1],[1,0],[1,1]],dtype=np.float32)
y_data=np.array([[0],[1],[1],[1]],dtype=np.float32)

X=tf.placeholder(tf.float32)
Y=tf.placeholder(tf.float32)

W=tf.Variable(tf.random_normal([2,1]),name='weight')
b=tf.Variable(tf.random_normal([1]),name='bias')


In [13]:
#Hypothesis using sigmoid : tf.div(1., 1.+tf.exp(tf.matmul(X,W)))
hypothesis=tf.sigmoid(tf.matmul(X,W)-b)
#cost/loss function
cost=-tf.reduce_mean(Y*tf.log(hypothesis)+(1-Y)*tf.log(1-hypothesis))
train= tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [15]:
#Accuracy coumputation
#True if hypothesis>0.2 else False
predicted = tf.cast(hypothesis > 0.2,dtype=tf.float32)
accuracy=tf.reduce_mean(tf.cast(tf.equal(predicted,Y),dtype=tf.float32))

#Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={X:x_data,Y:y_data})
        if step % 500 ==0:
            print("step:",step,"\ncost:",sess.run(cost,feed_dict={X:x_data,Y:y_data}),
                 '\nweight:\n',sess.run(W),'\nbias:\n',sess.run(b))
            h,c,a=sess.run([hypothesis,predicted,accuracy],feed_dict={X:x_data, Y:y_data})
            print("Hypothesis:\n",h,"\nCorrect:\n",c,"\nAccuracy:",a)

step: 0 
cost: 1.1006881 
weight:
 [[-0.76882756]
 [-0.5821441 ]] 
bias:
 [-0.02948663]
Hypothesis:
 [[0.5073711 ]
 [0.3652481 ]
 [0.3231483 ]
 [0.21057133]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy: 0.75
step: 500 
cost: 0.16977768 
weight:
 [[2.6402922]
 [2.671434 ]] 
bias:
 [0.6817504]
Hypothesis:
 [[0.33587074]
 [0.87970966]
 [0.8763751 ]
 [0.9903392 ]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy: 0.75
step: 1000 
cost: 0.09449383 
weight:
 [[3.903994 ]
 [3.9145243]] 
bias:
 [1.410276]
Hypothesis:
 [[0.1961905 ]
 [0.9244391 ]
 [0.9237003 ]
 [0.99835473]] 
Correct:
 [[0.]
 [1.]
 [1.]
 [1.]] 
Accuracy: 1.0
step: 1500 
cost: 0.06435035 
weight:
 [[4.7135615]
 [4.718565 ]] 
bias:
 [1.8452685]
Hypothesis:
 [[0.13642938]
 [0.94651043]
 [0.9462566 ]
 [0.9994931 ]] 
Correct:
 [[0.]
 [1.]
 [1.]
 [1.]] 
Accuracy: 1.0
step: 2000 
cost: 0.04843752 
weight:
 [[5.3041263]
 [5.3069916]] 
bias:
 [2.1549783]
Hypothesis:
 [[0.10386693]
 [0.95898795]
 [0.9588751 ]
 [0.9997875 ]] 
Correct:
 [[0

#### 대략적 결과 해석

step: 10000   

cost: 0.009356036 

weight:

[[8.649058]    <- w1

[8.649164]]    <- w2

bias:

[3.8593543]    <- 세타 값

Hypothesis:

[[0.02064635]

[0.99175453]

[0.9917536 ]

[0.99999857]] 

Correct:

[[0.]

[1.]

[1.]

[1.]] 

Accuracy: 1.0 <- Accuracy : 1.0 으로 다 맞추고 있다,


0 < bias(세타)/w2 < 1 을 만족한다,

X2=(w1/w2)X1 + bias/w2 에 대입하면 hyperplane을 구할 수 있다.

#### hyperplane : 

#### X2 = (8.649058 / 8.649164)X1 + (3.8593543 / 3.8593543)